### ISSUE TITLE
zpool info still reported after dd

### ISSUE THREAD

**Issue by tanabarr** [intel-hpdd/intel-manager-for-lustre#282]
between tests in SSI for IML the zpools and child datasets are removed and recreated, I have observed that the export command is run on a pool on all hosts and then the first host attempts to import. if this import fails then dd is run on the disk in order to clean it. Subsequently when listing zpools on the host that last had said pool imported, the pool and dataset still exists.

apparently the relevant sectors identifying zfs objects on the disk are two at the beginning and two at the end, so maybe dd needs to be run at the beginning and the end of the disk, not just at the beginning? reboot or clearing cache are other options
another approach would be to try to destroy before trying to export, or to try to destroy on the host it is currently exported on if we cannot import on the first host

it should be noted that this is all after the clear_ha script is run, so no active mounts should exist to stop the pool from being exported

https://forums.freebsd.org/threads/29739/

**Comment by tanabarr** [comment]
[chroma_test.log.txt](https://github.com/intel-hpdd/intel-manager-for-lustre/files/1304844/chroma_test.log.txt)

**Comment by brianjmurrell** [comment]
> it should be noted that this is all after the clear_ha script is run, so no active mounts should exist to stop the pool from being exported

It's worth noting that I am debugging issues with what looks at this point like unmounting issues with lustre in #250.  Perhaps this is related.

Regardless, it would be **very** useful to have an IML-less reproducer documented here to both demonstrate what the actual problem is as well as how it presents itself.

It would also greatly help somebody picking this ticket up to have a clear understanding of the problem outside of the context of IML and helps get them up and running to solve it with steps to reproduce it.

**Comment by tanabarr** [comment]
#86 #289

**Comment by tanabarr** [comment]
#244 will remove the use of dd to clear disks used to create zfs devices and instead employ zpool labelclear

**Comment by tanabarr** [comment]
#314 contained changes to stop using dd to clear disks we use for zfs and has been merged to master
