### ISSUE TITLE
How to get read/write bandwidth from IML over api, cli or database

### ISSUE THREAD

**Issue by wutaizeng** [intel-hpdd/intel-manager-for-lustre#449]
### Description 

We want to use our self gui to display lustre read/write bandwidth, so we need to get it from IML over api, cli or database.

### Repro

na

### Version

What version of IML?

4.0.0.0

What Operating System?

RHEL

What Operating System version?

7.4

**Comment by jgrund** [comment]
Hi @wutaizeng,

The easiest way to do this is to use the same REST API the IML GUI uses.

You can send a HTTP `GET` to the metrics endpoint for aggregated target data. Here is an example that will fetch summed read / write bytes for all targets since midnight January 31st 2018 UTC:

```https://url-to-manager-here/api/target/metric/?kind=OST&reduce_fn=sum&metrics=stats_read_bytes,stats_write_bytes&begin=2018-01-31T00:00:00.000Z```

Keep in mind you will need to send a `Content-Type: application/json` header with the request, or append `format=json` to the querystring.

Hope this helps.
