### ISSUE TITLE
Make sure to disable chroma-agent before rebooting

### ISSUE THREAD

**Issue by jgrund** [intel-hpdd/intel-manager-for-lustre#477]
In:

https://github.com/intel-hpdd/intel-manager-for-lustre/blob/db03404348da2712ac4b075375b574d83ff56326/chroma-manager/tests/integration/existing_filesystem_configuration/utils/create_lustre_filesystem.py#L115-L118

we restart the agents *after* we stop the agent daemons.

This ends up starting the agents again, which is going to cause us issues.

use ```systemctl disable chroma-agent``` on each node before rebooting. We'll want to make sure to enable them as well when we start the agents back up again.

**Comment by tanabarr** [comment]
probably due to device scanning importing (sometimes with the force flag) and exporting pools, while this shouldn't be able to cause corruption due to double imports with MMP enabled there is a fair chance there are situations during the restart process where a disk might be wiped when imported on another note during agent device scanning

**Comment by jgrund** [comment]
I think we can keep everything running in 4.1. Closing.
