### ISSUE TITLE
Unable to deploy agent to server

### ISSUE THREAD

**Issue by Zubrania** [intel-hpdd/intel-manager-for-lustre#501]
### Description 

Unable  to deploy  agent to the server 

### Repro

What steps were taken leading to this issue
Adding new server to IML

```
Arguments
{
  "host": "new-mgs-mds-01",
  "profile_name": "default",
  "token": "RegistrationToken object"
}

Backtrace

Failed to register host new-mgs-mds-01: rc=0
''
'/root/.bashrc: line 1: .bashrc: command not found
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:06 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:07 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:08 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:09 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0
curl: (35) Proxy CONNECT followed by 789 bytes of opaque data. Data ignored (known bug #39)
'
```

### Version

What version of IML?
4.0.3.0
What Operating System?
IML is installed on CentOS 
Servers are RHEL
What Operating System version?
IML OS CentOS 7.4
Servers are RHEL 7.4

**Comment by brianjmurrell** [comment]
Do you have a proxy server in your environment?

**Comment by Zubrania** [comment]
Yes, thank you,  did not think  about  that

**Comment by brianjmurrell** [comment]
@Zubrania: So just to close out on this, you need to exempt the IML nodes from your proxy configuration so that communication between the nodes doesn't go through your proxy server.  Using the defacto standard environment variables this can be done with `no_proxy`.

Your mileage will vary depending on how you are configuring your nodes to use the proxy.

Feel free to reopen this issue if you need further help about it.

**Comment by Zubrania** [comment]
Hello Brian

Can you please share the link to the iml documentation or config file where no_proху parameter can be set? 
Thank you

Kind Regards
Dzmitryj Jakavuk

**Comment by brianjmurrell** [comment]
@Zubrania: `no_proxy` is not an IML configuration item.  It's a general proxy environment setting on Linux, if you are even using environment settings for your proxy.  I only provided that example as a starting point for you discover how proxing is configured in your own environment so that you can exempt internal network nodes from using the proxy.

So really, however you are exempting the rest of your internal network nodes from using the proxy will work equally well for IML.
