### ISSUE TITLE
Ethernet Based Resources in IML

### ISSUE THREAD

**Issue by UnknownNet** [intel-hpdd/intel-manager-for-lustre#585]
### Description 

I have an IML managed system using ethernet for it's high performance network. Losing a link on an OSS node does not seem to trigger a failover event. Does IML (PCS) include any ping-type resource definition to ping over that ethernet interface to check a keepalive? Can we add PCS resources/rules to an existing system to increase resiliency, or will IML rewrite the rules (or just reject the node if it sees new rules)?

### Repro

As the system is in production, it's difficult to reproduce without affecting users. The original issue started with a link going down on an OSS node.

### Version

What version of IML? 4.0.4.0
What Operating System? CentOS
What Operating System version? 7

**Comment by brianjmurrell** [comment]
IML does not at this time monitor the LNet health of the storage servers and fail over resources if it's unhealthy.  This is a area that we know needs improvement but such an improvement is not yet scheduled.

We'd be most willing to take a code contribution to fill that feature gap if your needs for it are urgent enough for you to take a stab at coding it up.

Due to the complexity and abundance of deviations from the standard IML Pacemaker configuration, we unfortunately cannot be sure that adding additional Pacemaker resources to the ones that IML configures won't interfere with a future upgrade of IML.

If you do go down that path, it would be suggested to remove any such additional resources prior to any upgrade of IML on either the manager or the storage servers and put them back after the upgrade.

**Comment by UnknownNet** [comment]
This makes sense, thanks for the pointers. If I come up with something code-wise, I'll make sure and pass it along.
